apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: n5nqg115l-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/n5nqg115l-java-quarkus-gitops